### PR TITLE
fix(auth): Better type hierarchies for Auth API

### LINKED ISSUE #1267: Incorrect typing on `createUser` api in admin.auth leads to broken multi-factor auth
* Operating System version: Mac OS 11.2.3
  * Firebase SDK version: 9.7.0
  * Firebase Product: auth
  * Node.js version: 12.21.0
  * NPM version: 7.7.0

### [REQUIRED] Step 3: Describe the problem

Typescript types are incorrect for `CreateMultiFactorInfoRequest` and `CreatePhoneMultiFactorInfoRequest` in `admin.auth.createUser`. I expect to be able to pass in a phone number but am not allowed by the type system. Instead, I have to cast the type as `any`.

#### Steps to reproduce:

```
admin.auth.createUser({
  displayName: 'somebody',
  email: 'some@one.com'
  emailVerified: true,
  multiFactor: { enrolledFactors: [{ factorId: 'phone', phoneNumber: request.phoneNumber }] }
}
```

This yields the error 
  
image

You can work around this by casting the object to an `any`, but the type system is still wrong here.

This was also raised in https://github.com/firebase/firebase-admin-node/issues/1048 but for some reason that ticket was closed by the OP.

As a side-note, it feels like the code was written by someone who thought that extending a typescript `interface` would mean that instances of the derived class can be passed in instead of the base class, but with structural typing, this is not allowed.

### PR DESCRIPTION
**Pull request by hiranya911**
Defining `AuthProviderConfig`, `CreateMultiFactorInfoRequest`, and `UpdateMultiFactorInfoRequest` as union types. 

I'd also like to the move the `factorId` field to the child interfaces, and further restrict its domain (`string` --> `'phone'`), but this seems to be a breaking change (a couple of compilation issues detected in tests). So for now I'm keeping this field as is. 

Resolves #1267

### CODE REVIEW

File: src/auth/index.ts [hunk 1]
```diff
@@ -463,14 +469,20 @@ export namespace auth {
...
 
     /**
      * The phone number associated with a phone second factor.
      */
     phoneNumber: string;
   }
 
+  /**
+   * Type representing the properties of a user enrolled second factor
+   * for an `CreateRequest`.
```
Comment (bojeil-google) [inline src/auth/index.ts:482]: a `CreateRequest`.

**Review by bojeil-google — APPROVED** [review]

**Review by lahirumaramba — APPROVED** [review]
LGTM! Thanks!
Should we get the reference docs reviewed?

File: src/auth/index.ts (hunk 1 above)
Comment (hiranya911) [reply src/auth/index.ts]: Done

**Comment by hiranya911** [comment]
@egilmorez can you take a look at the comment updates in auth/index.ts?

File: src/auth/index.ts [hunk 2]
```diff
@@ -367,14 +367,20 @@ export namespace auth {
...
+  export interface UpdatePhoneMultiFactorInfoRequest extends BaseUpdateMultiFactorInfoRequest {
 
     /**
      * The phone number associated with a phone second factor.
      */
     phoneNumber: string;
   }
 
+  /**
+   * Type representing the properties of a user enrolled second factor
```
Comment (egilmorez) [inline src/auth/index.ts:379]: This would be clearer as "user-enrolled" 

There are 7 other instances in the file; if that's a PITA, I can do it in a follow-on.

**Review by egilmorez — APPROVED** [review]
One possible nit, LG, thanks!

File: src/auth/index.ts (hunk 2 above)
Comment (hiranya911) [reply src/auth/index.ts]: Fixed
